openapi: 3.0.3
info:
  title: Products APIs Definition
  description: |
    # About Us
    ***Worklog*** application for logging work for company customers.
  version: 0.0.1
  contact:
    name: API Support
    email: rabr@softwaremind.com
  x-custom-info:
    comment: Some comments
    authors:
      - name: John Doe
        email: rabr@softwaremind.com
tags:
  - name: Customers
    description: Categories-related operations
servers:
  - url: 'http://localhost:8080'
paths:
  /customer:
    $ref: './paths/customer/customer.yml'
  /customer/{customerId}:
    $ref: './paths/customer/customer_customerId.yml'